require("autocommands")
require("keybinds")
require("settings")

-- Plugin configurations
require("plugins/bufferline")
require("plugins/comment")
require("plugins/indent-blankline")
require("plugins/kanagawa")
require("plugins/lualine")
require("plugins/luasnip")
require("plugins/null-ls")
require("plugins/nvim-autopairs")
require("plugins/nvim-cmp")
require("plugins/nvim-colorizer")
require("plugins/nvim-lspconfig")
require("plugins/nvim-surround")
require("plugins/nvim-tree")
require("plugins/nvim-treesitter")
require("plugins/nvim-trevJ")
require("plugins/packer")
require("plugins/presence")
require("plugins/telescope")
require("plugins/vimtex")
